# Generated by Django 4.0.8 on 2023-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcweave', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedZipFile',
        ),
        migrations.AddField(
            model_name='arcweaveproject',
            name='zip_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
