# Generated by Django 4.0.8 on 2023-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcweave', '0002_delete_uploadedzipfile_arcweaveproject_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcweaveproject',
            name='zip_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
