# Generated by Django 4.0.8 on 2023-06-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcweave', '0003_alter_arcweaveproject_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcweaveproject',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
